export const CHATS_REQUEST = "CHATS_REQUEST";
export const CHATS_SUCCESS = "CHATS_SUCCESS";
export const CHATS_FAIL = "CHATS_FAIL";
export const USER_CHATS_SEARCH_REQUEST = "USER_CHATS_SEARCH_REQUEST";
export const USER_CHATS_SEARCH_SUCCESS = "USER_CHATS_SEARCH_SUCCESS";
export const USER_CHATS_SEARCH_FAIL = "USER_CHATS_SEARCH_FAIL";

export const ACCESS_REQUEST = "USER_CHATS_SEARCH_REQUEST";
export const ACCESS_SUCCESS = "USER_CHATS_SEARCH_SUCCESS";
export const ACCESS_FAIL = "USER_CHATS_SEARCH_FAIL";