export const CHATS_REQUEST = "CHATS_REQUEST";
export const CHATS_SUCCESS = "CHATS_SUCCESS";
export const CHATS_FAIL = "CHATS_FAIL";
export const USER_CHATS_SEARCH_REQUEST = "USER_CHATS_SEARCH_REQUEST";
export const USER_CHATS_SEARCH_SUCCESS = "USER_CHATS_SEARCH_SUCCESS";
export const USER_CHATS_SEARCH_FAIL = "USER_CHATS_SEARCH_FAIL";

export const ACCESS_REQUEST = "ACCESS_REQUEST_REQUEST";
export const ACCESS_SUCCESS = "ACCESS_REQUEST_SUCCESS";
export const ACCESS_FAIL = "ACCESS_REQUEST_FAIL";

export const CREATE_GROUP_CHAT_REQUEST = "CREATE_GROUP_CHAT_REQUEST";
export const CREATE_GROUP_CHAT_SUCCESS = "CREATE_GROUP_CHAT_SUCCESS";
export const CREATE_GROUP_CHAT_FAIL = "CREATE_GROUP_CHAT_FAIL";

export const SELECTED_CHAT_REQUEST = "SELECTED_CHAT_REQUEST";
export const SELECTED_CHAT_SUCCESS = "SELECTED_CHAT_SUCCESS";
export const SELECTED_CHAT_FAIL =    "SELECTED_CHAT_FAIL";

export const SELECT_CHAT = "SELECT_CHAT";